### PR TITLE
add variable netq_repo_version and netq_repo

### PR DESCRIPTION
**Pull request by russelltadams**
to allow explicit configuration of netq repo version...

One issue I am not able to account for yet, is removing the old repo version that might be in the sources file...  the apt_repository repo module only adds or removes specific entries...  should we clobber the whole file? I am not sure what's best here.  Any suggestions?

### CODE REVIEW

**Comment by davidmnoriega** [comment]
Maybe add an additional task that removes the netq-latest repo if it exists?

**Comment by russelltadams** [comment]
@davidmnoriega yes, that will work to remove "latest", and I have done that locally to clean up our environments in this case, but eventually a user will need to move from 1.x to 2.1 to 2.x. and so on...  How to keep up house cleaning when the only new configured version is known, and the old version is not, and should be removed?

It's a shame just using "latest" doesn't result in it knowing which agent to use, but it just can't, Cumulus 3.7.x can work with both 1.4 and 2.1 but the agent has to match the server.

**Comment by russelltadams** [comment]
So some task to remove any "other" version if it exists... seem like the only way to is check the version, and if it doesn't match, remove it? Not sure how best to do that.

**Comment by russelltadams** [comment]
@davidmnoriega  We will leave removing the old repo out of scope for now and put a note in the readme.

**Comment by davidmnoriega** [comment]
You haven't actually add a note that the role will not delete previous repo definitions, such as in the case of changing the netq version, it'll just add a whole new repo def

**Review by davidmnoriega — APPROVED** [review]

**Pull request merged**
